version: '3.8'
services:

  # PHP Service
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    image: wibscreen-laravel-app
    container_name: wibscreen-app
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    volumes:
      - ./:/var/www
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - wibscreen-network

  # Nginx Service
  web:
    image: nginx:alpine
    container_name: wibscreen-web
    restart: unless-stopped
    tty: true
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - wibscreen-network

  # MySQL Service
  db:
    image: mysql:8.0
    container_name: wibscreen-db
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: Wibscreen
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_PASSWORD: 1234
      MYSQL_USER: laravel_user
    volumes:
      - wibscreen-dbdata:/var/lib/mysql
    networks:
      - wibscreen-network

  # Mailpit Service
  mailpit:
    image: axllent/mailpit
    container_name: wibscreen-mailpit
    restart: unless-stopped
    ports:
      - "8025:8025"
      - "1025:1025"
    networks:
      - wibscreen-network

networks:
  wibscreen-network:
    driver: bridge

volumes:
  wibscreen-dbdata:
    driver: local
